"""icelake: accurate, scalable agentic memory for Discord bots.

Quickstart::

    from icelake import Memory, MemoryConfig, MessageEvent

    memory = Memory(MemoryConfig(
        storage="sqlite:///memory.db",
        llm="openai://$KEY@openrouter.ai/api/v1?model=google/gemini-2.5-flash",
    ))
    async with memory:
        await memory.observe(event)
        ctx = await memory.prompt_context(guild_id=g, asker_id=u, text=msg)
        system_prompt += ctx.injection_block

"""

from importlib.metadata import version

from icelake.api.classify import CommandAction, UserMemoryCommand
from icelake.api.client import DiscordMemory, MemoryOverrides
from icelake.config import (
    BatchingConfig,
    BudgetsConfig,
    EmbeddingsConfig,
    EmbeddingsProvider,
    ExtractionConfig,
    LifecycleConfig,
    LlmConfig,
    MemoryConfig,
    ObserveConfig,
    PrivacyConfig,
    RetrievalConfig,
    StorageBackend,
    StorageConfig,
    WorkersConfig,
)
from icelake.errors import (
    BudgetExceededError,
    ConfigError,
    DiscordMemoryError,
    FactNotFoundError,
    LlmCapabilityError,
    SchemaValidationError,
    StorageUnavailableError,
    StructuredOutputError,
    SubjectNotAllowedError,
    WorkerNotRunningError,
)
from icelake.models import (
    CHANNELS_ALL,
    CHANNELS_DEFAULT,
    CHANNELS_DISCOVERY,
    AliasRecord,
    AliasSource,
    Attribution,
    AttributionType,
    BudgetStep,
    ChannelName,
    ChannelSet,
    Citation,
    EdgeKind,
    EntityKind,
    EntityRecord,
    FactCategory,
    FactHistoryEntry,
    FactHistoryKind,
    FactRecord,
    FactScope,
    GuildStats,
    HealthReport,
    HealthStatus,
    IgnoreReason,
    MemoryExport,
    MemoryTier,
    MessageEvent,
    MeterPurpose,
    MeterSnapshot,
    NeighborInfo,
    NodeType,
    ObserveReceipt,
    ObserveStatus,
    Page,
    Polarity,
    PromptContext,
    PurgeReport,
    RecallQuery,
    RecallResult,
    RecallWarning,
    RejectReason,
    RelationEdge,
    RelationVerb,
    Resolution,
    ResolvedCandidate,
    Scope,
    ScoreComponents,
    ScoredFact,
    SimilarUser,
    SourceRef,
    SourceRole,
    StanceSummary,
    channels,
)
from icelake.models.events import (
    BatchCompleted,
    ComponentDegraded,
    ExtractionFailed,
    FactCommitted,
    FactSupersededEvent,
)
from icelake.models.operations import ProposedEntity, ProposedFact, ProposedRelation
from icelake.ports.llm import (
    ChatLLM,
    ChatRequest,
    ChatResponse,
    Embedder,
    LlmMessage,
    MessageRole,
)
from icelake.ports.store import MemoryStore

__version__ = version("icelake")

# Public, transport-free name. ``DiscordMemory`` stays as the back-compat
# alias; the class itself is store/LLM-agnostic and Discord is an extra.
Memory = DiscordMemory

__all__ = [
    "CHANNELS_ALL",
    "CHANNELS_DEFAULT",
    "CHANNELS_DISCOVERY",
    "AliasRecord",
    "AliasSource",
    "Attribution",
    "AttributionType",
    "BatchCompleted",
    "BatchingConfig",
    "BudgetExceededError",
    "BudgetStep",
    "BudgetsConfig",
    "ChannelName",
    "ChannelSet",
    "ChatLLM",
    "ChatRequest",
    "ChatResponse",
    "Citation",
    "CommandAction",
    "ComponentDegraded",
    "ConfigError",
    "DiscordMemory",
    "DiscordMemoryError",
    "EdgeKind",
    "Embedder",
    "EmbeddingsConfig",
    "EmbeddingsProvider",
    "EntityKind",
    "EntityRecord",
    "ExtractionConfig",
    "ExtractionFailed",
    "FactCategory",
    "FactCommitted",
    "FactHistoryEntry",
    "FactHistoryKind",
    "FactNotFoundError",
    "FactRecord",
    "FactScope",
    "FactSupersededEvent",
    "GuildStats",
    "HealthReport",
    "HealthStatus",
    "IgnoreReason",
    "LifecycleConfig",
    "LlmCapabilityError",
    "LlmConfig",
    "LlmMessage",
    "Memory",
    "MemoryConfig",
    "MemoryExport",
    "MemoryOverrides",
    "MemoryStore",
    "MemoryTier",
    "MessageEvent",
    "MessageRole",
    "MeterPurpose",
    "MeterSnapshot",
    "NeighborInfo",
    "NodeType",
    "ObserveConfig",
    "ObserveReceipt",
    "ObserveStatus",
    "Page",
    "Polarity",
    "PrivacyConfig",
    "PromptContext",
    "ProposedEntity",
    "ProposedFact",
    "ProposedRelation",
    "PurgeReport",
    "RecallQuery",
    "RecallResult",
    "RecallWarning",
    "RejectReason",
    "RelationEdge",
    "RelationVerb",
    "Resolution",
    "ResolvedCandidate",
    "RetrievalConfig",
    "SchemaValidationError",
    "Scope",
    "ScoreComponents",
    "ScoredFact",
    "SimilarUser",
    "SourceRef",
    "SourceRole",
    "StanceSummary",
    "StorageBackend",
    "StorageConfig",
    "StorageUnavailableError",
    "StructuredOutputError",
    "SubjectNotAllowedError",
    "UserMemoryCommand",
    "WorkerNotRunningError",
    "WorkersConfig",
    "channels",
]
