"""Boundary models exported for consumers and adapters."""

from __future__ import annotations

from discord_memory.models.admin import (
    BudgetStep,
    ComponentHealth,
    GuildStats,
    HealthReport,
    HealthStatus,
    MemoryExport,
    MeterSnapshot,
    PurgeReport,
)
from discord_memory.models.common import FrozenModel, Page, TokenUsage
from discord_memory.models.events import (
    IgnoreReason,
    MessageEvent,
    ObserveReceipt,
    ObserveStatus,
    RejectReason,
)
from discord_memory.models.facts import (
    Attribution,
    AttributionType,
    FactCategory,
    FactHistoryEntry,
    FactRecord,
    MemoryTier,
    SourceRef,
    SourceRole,
)
from discord_memory.models.graph import (
    EdgeKind,
    EntityKind,
    EntityRecord,
    NeighborInfo,
    NodeType,
    Polarity,
    RelationEdge,
    StanceSummary,
)
from discord_memory.models.identity import (
    AliasRecord,
    AliasSource,
    Resolution,
    ResolvedCandidate,
)
from discord_memory.models.retrieval import (
    CHANNELS_ALL,
    CHANNELS_DEFAULT,
    CHANNELS_DISCOVERY,
    ChannelName,
    Citation,
    PromptContext,
    RecallQuery,
    RecallResult,
    RecallWarning,
    Scope,
    ScoreComponents,
    ScoredFact,
    channels,
    render_citation_tag,
)

__all__ = [
    "CHANNELS_ALL",
    "CHANNELS_DEFAULT",
    "CHANNELS_DISCOVERY",
    "AliasRecord",
    "AliasSource",
    "Attribution",
    "AttributionType",
    "BudgetStep",
    "ChannelName",
    "Citation",
    "ComponentHealth",
    "EdgeKind",
    "EntityKind",
    "EntityRecord",
    "FactCategory",
    "FactHistoryEntry",
    "FactRecord",
    "FrozenModel",
    "GuildStats",
    "HealthReport",
    "HealthStatus",
    "IgnoreReason",
    "MemoryExport",
    "MemoryTier",
    "MessageEvent",
    "MeterSnapshot",
    "NeighborInfo",
    "NodeType",
    "ObserveReceipt",
    "ObserveStatus",
    "Page",
    "Polarity",
    "PromptContext",
    "PurgeReport",
    "RecallQuery",
    "RecallResult",
    "RecallWarning",
    "RejectReason",
    "RelationEdge",
    "Resolution",
    "ResolvedCandidate",
    "Scope",
    "ScoreComponents",
    "ScoredFact",
    "SourceRef",
    "SourceRole",
    "StanceSummary",
    "TokenUsage",
    "channels",
    "render_citation_tag",
]
