"""discord-memory: accurate, scalable agentic memory for Discord bots.

Quickstart::

    from discord_memory import DiscordMemory, MemoryConfig, MessageEvent

    memory = DiscordMemory(MemoryConfig(
        storage="sqlite:///memory.db",
        llm="openai://$KEY@openrouter.ai/api/v1?model=google/gemini-2.5-flash",
    ))
    async with memory:
        await memory.observe(event)
        ctx = await memory.prompt_context(guild_id=g, asker_id=u, text=msg)
        system_prompt += ctx.injection_block

See docs/API.md for the complete consumer contract and docs/PLAN.md for design.
"""

from discord_memory.api.classify import CommandAction, UserMemoryCommand
from discord_memory.api.client import DiscordMemory
from discord_memory.config import (
    BatchingConfig,
    BudgetsConfig,
    EmbeddingsConfig,
    ExtractionConfig,
    LifecycleConfig,
    LlmConfig,
    MemoryConfig,
    PrivacyConfig,
    RetrievalConfig,
    StorageConfig,
    WorkersConfig,
)
from discord_memory.errors import (
    BudgetExceededError,
    ConfigError,
    DiscordMemoryError,
    FactNotFoundError,
    IdentityAmbiguousError,
    SchemaValidationError,
    StorageUnavailableError,
    SubjectNotAllowedError,
    WorkerNotRunningError,
)
from discord_memory.models import (
    CHANNELS_ALL,
    CHANNELS_DEFAULT,
    CHANNELS_DISCOVERY,
    Attribution,
    AttributionType,
    ChannelName,
    Citation,
    EdgeKind,
    EntityRecord,
    FactCategory,
    FactHistoryEntry,
    FactRecord,
    GuildStats,
    HealthReport,
    IgnoreReason,
    MemoryExport,
    MemoryTier,
    MessageEvent,
    NeighborInfo,
    NodeType,
    ObserveReceipt,
    ObserveStatus,
    Polarity,
    PromptContext,
    PurgeReport,
    RecallQuery,
    RecallResult,
    RecallWarning,
    RejectReason,
    RelationEdge,
    Resolution,
    ResolvedCandidate,
    Scope,
    ScoreComponents,
    ScoredFact,
    SourceRef,
    StanceSummary,
    channels,
)
from discord_memory.models.events import (
    BatchCompleted,
    BudgetWarning,
    ComponentDegraded,
    ExtractionFailed,
    FactCommitted,
    FactSupersededEvent,
)

__version__ = "0.1.0"

__all__ = [
    "CHANNELS_ALL",
    "CHANNELS_DEFAULT",
    "CHANNELS_DISCOVERY",
    "Attribution",
    "AttributionType",
    "BatchCompleted",
    "BatchingConfig",
    "BudgetExceededError",
    "BudgetWarning",
    "BudgetsConfig",
    "ChannelName",
    "Citation",
    "CommandAction",
    "ComponentDegraded",
    "ConfigError",
    "DiscordMemory",
    "DiscordMemoryError",
    "EdgeKind",
    "EmbeddingsConfig",
    "EntityRecord",
    "ExtractionConfig",
    "ExtractionFailed",
    "FactCategory",
    "FactCommitted",
    "FactHistoryEntry",
    "FactNotFoundError",
    "FactRecord",
    "FactSupersededEvent",
    "GuildStats",
    "HealthReport",
    "IdentityAmbiguousError",
    "IgnoreReason",
    "LifecycleConfig",
    "LlmConfig",
    "MemoryConfig",
    "MemoryExport",
    "MemoryTier",
    "MessageEvent",
    "NeighborInfo",
    "NodeType",
    "ObserveReceipt",
    "ObserveStatus",
    "Polarity",
    "PrivacyConfig",
    "PromptContext",
    "PurgeReport",
    "RecallQuery",
    "RecallResult",
    "RecallWarning",
    "RejectReason",
    "RelationEdge",
    "Resolution",
    "ResolvedCandidate",
    "RetrievalConfig",
    "SchemaValidationError",
    "Scope",
    "ScoreComponents",
    "ScoredFact",
    "SourceRef",
    "StanceSummary",
    "StorageConfig",
    "StorageUnavailableError",
    "SubjectNotAllowedError",
    "UserMemoryCommand",
    "WorkerNotRunningError",
    "WorkersConfig",
    "channels",
]
